sudo: required

services:
  - docker

env: DOCKER_IMAGE=paulinus/opensfm-docker-base:manylinux1_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/python/build-wheels.sh
  - ls wheelhouse/

deploy:
  provider: releases
  api_key:
    secure: "nbu4tqTBqHg1bSJtSZyKetfsJcnvXfPH2I91mTSO5qhr3aIqPc5MWv/GwZFEITkAsyIKVWcaf0FFNynW5QqJBvvCiir3h9hwel6ORpAEsR2u2QpU5Y5lyjkxEAjVSeqoR9JLLLk/1xyS9sCCKWgCQNOcAaOhYlxcs0B2ew2hr6ZTd7pvWymxs3Xls3Bb6speDdlkqxtUbJt0ylPkj5wzHcS+vKczc2qDvrQEzuvLL7l+wXCPWk+ueBdKahH/JON+UPmdNI/UobjPEYA+ynwB1ykZw9OiUMHsvvH5xBeR6mM5vPzr7AXBmiaUcWQd37sd3a6Rk0tOF3qtPXCk2Yl03mlf3p2OOfaYeN/oPlADt7G3E6nIOVRg0LX65N0JPxvnGXFnkWa+5ATppiePp26EftXjLPLfj3ogWpUo8jVxgM1/nMsgcGY4Q3FRcMpl8SqyMpclH2RI9LhFhQHq23LOPM6d2bDOhosdB8npz9B7lE6UPSfF2LqANZivckPpUi2tXQ93LTEMj+aDZjk3CywNo2mHWFDIIvVWBnB1nL6K5V1GZTBVob3ew3z9ZPNAFZPTr5WfXruEvpK0ztTFKvnSPMVVk0Ud4MbrNOyLx0G5NxfbgTedD7fLfpiCGz581AXibyHj07r5P4e4lVqNubevtIGgOzKrVPUl/wShLycMAFc="
  file_glob: true
  file: wheelhouse/*.whl
  skip_cleanup: true
  draft: true
  on:
    branch: python-wheels
